

services:
  yagna1:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - YAGNA_VERSION=0.15.0
    command: yagna service run
    environment:
      GSB_URL: tcp://0.0.0.0:11000
      YAGNA_AUTOCONF_ID_SECRET: ${ETH_PRIVATE_KEY_1}
      YAGNA_PUBLIC_ADDRESS: ${ETH_ADDRESS_1}
      YA_NET_TYPE: central
    ports:
      - 11000:11000
    cap_add:
      - NET_ADMIN
  yagna2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - YAGNA_VERSION=0.15.0
    command: yagna service run
    environment:
      GSB_URL: tcp://0.0.0.0:11001
      YAGNA_AUTOCONF_ID_SECRET: ${ETH_PRIVATE_KEY_2}
      YAGNA_PUBLIC_ADDRESS: ${ETH_ADDRESS_2}
      YA_NET_TYPE: central
    ports:
      - 11001:11001
    cap_add:
      - NET_ADMIN
