

name: Integration tests

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "42 3 * * *"

jobs:
  golem-ftp:
    name: Golem ftp build only
    timeout-minutes: 20

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Build golem ftp
        run: cargo build --profile=release-fast

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: gftp
          path: target/release-fast/gftp

  publish1:
    name: Publish/download file
    timeout-minutes: 20

    runs-on: ubuntu-latest
    needs: golem-ftp

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: gftp

      - name: Run dockers
        run: |
          cd integration
          docker-compose up -d
          sleep 10

      - name: Generate test file
        run: |
          cd integration
          python gen_random.py

      - name: Publish file
        run: |
          ./gftp publish integration/random_file.txt &
          sleep 3
        env:
          GSB_URL: tcp://127.0.0.1:11000
          GFTP_PROGRESS_INTERVAL: 5000

      - name: Download file
        run: |
          ./gftp download gftp://0x7c51df62f74dfa80599ef30219a045b3a58cb724/5f9f37dfdbe11ad9e28a975b9a0b64566de62bd6 integration/random_file2.txt
        env:
          GSB_URL: tcp://127.0.0.1:11001
          GFTP_PROGRESS_INTERVAL: 5000
